#!/usr/bin/env bash

# This file is generated by `code-gen`. Any change in this file could be override

set -e

PACKAGE=subfind
VERSION=4.5.3

rm ../subfind_4.5.3-1_amd64.deb || true

dpkg-buildpackage -us -uc

sudo apt-get remove -y subfind || true
sudo dpkg -i ../subfind_4.5.3-1_amd64.deb

test -x /opt/venvs/subfind/bin/subfind-web
/opt/venvs/subfind/bin/pip list

echo Expect service script exists
test -x /lib/systemd/system/subfind.service

echo Done